name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy over SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e
            echo "Pulling latest code..."
            cd ~/MERN_RabbitMQ_Deployment
            git fetch --all
            git reset --hard origin/main

            echo "Stopping old containers..."
            /usr/local/bin/docker-compose down

            echo "Building & starting containers..."
            /usr/local/bin/docker-compose up -d --build

            echo "Deployment complete. Running containers:"
            docker ps
